### ISSUE TITLE
Pretrained ViViT weights

### ISSUE THREAD

**Issue by Anirudh257** [mx-mark/VideoTransformer-pytorch#1]
Hi, thanks for releasing your code. Do you have the pretrained weights for ViViT in torch? I found Timesformer weights only.

**Comment by mx-mark** [comment]
Thanks for your attention.We will release the ViViT-B model pretrained on K400 later.

在 2022-01-28 19:20:20，Anirudh Thatipelli ***@***.***> 写道：

Hi, thanks for releasing your code. Do you have the pretrained weights for ViViT in torch? I found Timesformer weights only.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
