### ISSUE TITLE
Request code for finetune with self-supervised pretrained weights

### ISSUE THREAD

**Issue by WHlTE-N0lSE** [mx-mark/VideoTransformer-pytorch#11]
I tried to do self-supervised experiments with your code, but ran into a lot of problems during the fine-tuning stage. Can you share your MVIT finetune code? Thank you！

**Comment by mx-mark** [comment]
@WHlTE-N0lSE you can refer the start script at https://github.com/mx-mark/VideoTransformer-pytorch/blob/main/README.md#:~:text=%23%20finetune%20with%20maskfeat,TRAIN_DATA_PATH%20%5C%0A%09%2Dval_data_path%20%24VAL_DATA_PATH

**Comment by WHlTE-N0lSE** [comment]
Ok! I'll try it.

**Comment by Enclavet** [comment]
@mx-mark 

With the latest code changes, I dont think this combination of hparams works anymore:

-objective 'supervised' \
-arch 'timesformer' \

I'm getting NotImplemented exceptions which appear to be when trying to use: build_finetune_optimizer with arch other than mvit.

Looking backwards this depended on is_pretrain that is passed in from model_trainer.py:

is_pretrain = not (self.configs.objective == 'supervised')

**Comment by mx-mark** [comment]
@Enclavet oh, thanks for your reply about the problem. There are some code transfer issues that the timesformer and vivit have been classified to pretrain not finetune stage with a moderate finetune recipe before. And we do not adapt the new finetune recipe to these two models.
