### ISSUE TITLE
Command for maskfeat pretraining

### ISSUE THREAD

**Issue by WHlTE-N0lSE** [mx-mark/VideoTransformer-pytorch#12]
Request the pretraining command for maskfeat.This doesn't seem to be provided in the code. Thank you!

**Comment by mx-mark** [comment]
@WHlTE-N0lSE The pretraining repo of maskfeat may need to be optimized. Currently, the speed of data loader perform not well. Because the hog features extraction occupy most of time.

**Comment by WHlTE-N0lSE** [comment]
The speed is acceptable, but what is the shell command of maskfeat pretraining?

**Comment by mx-mark** [comment]
@WHlTE-N0lSE We have alleviated the speed problem in maskfeat. The shell command can be found here https://github.com/mx-mark/VideoTransformer-pytorch#training
