### ISSUE TITLE
AttributeError: 'VideoTransformer' object has no attribute 'weight_decay'

### ISSUE THREAD

**Issue by Enclavet** [mx-mark/VideoTransformer-pytorch#15]
I got this error until I changed the following model_trainer.py:

param_group["weight_decay"] = self._get_momentum(base_value=self.weight_decay, final_value=self.configs.weight_decay_end)

to

param_group["weight_decay"] = self._get_momentum(base_value=self.configs.weight_decay, final_value=self.configs.weight_decay_end)

**Comment by mx-mark** [comment]
@Enclavet Thansks for your reporting about this problem.

**Comment by mx-mark** [comment]
@Enclavet Thanks for your reporting about this problem.
