### ISSUE TITLE
AssertionError：When loading annotation，an assertion error for label appears

### ISSUE THREAD

**Issue by yanmingchao2** [mx-mark/VideoTransformer-pytorch#16]
I use maskfeat for pre-training according to the author's settings, and the train_data_path is k400_classmap.json.
I didn't make any other changes to code.
Then the following assertion error occurred.

![image](https://user-images.githubusercontent.com/49579756/163384686-4b2cdd3c-b16c-4f89-b645-510d89e4d98e.png)
![image](https://user-images.githubusercontent.com/49579756/163384752-d2010302-6805-491e-8e71-06b361c17c7b.png)

Thank you for your help!

**Comment by yanmingchao2** [comment]
The traceback is shown below:

Traceback (most recent call last):
  File "/home/yanmingchao/VideoTransformer-pytorch/model_pretrain.py", line 257, in <module>
    single_run()
  File "/home/yanmingchao/VideoTransformer-pytorch/model_pretrain.py", line 253, in single_run
    trainer.fit(model, data_module)
  File "/home/administrator/.conda/envs/scenic/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/home/administrator/.conda/envs/scenic/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 715, in _run
    self.call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/home/administrator/.conda/envs/scenic/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1164, in call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/home/administrator/.conda/envs/scenic/lib/python3.9/site-packages/pytorch_lightning/core/datamodule.py", line 384, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/yanmingchao/VideoTransformer-pytorch/data_trainer.py", line 122, in setup
    self.train_dataset = self.get_dataset(
  File "/home/yanmingchao/VideoTransformer-pytorch/data_trainer.py", line 86, in get_dataset
    dataset = Kinetics(
  File "/home/yanmingchao/VideoTransformer-pytorch/dataset.py", line 143, in __init__
    self.data = load_annotations(annotation_path, self.configs.num_class, self.configs.num_samples_per_cls)
  File "/home/yanmingchao/VideoTransformer-pytorch/dataset.py", line 84, in load_annotations
    assert label, f'missing label in line: {line}'
AssertionError: missing label in line: {"abseiling": "0", "air_drumming": "1", "answering_questions": "2", "applauding": "3", "applying_cream": "4", "archery": "5", "arm_wrestling": "6", "arranging_flowers": "7", "assembling_computer": "8", "auctioning": "9", "baby_waking_up": "10", "baking_cookies": "11", "balloon_blowing": "12", "bandaging": "13", "barbequing": "14", "bartending": "15", "beatboxing": "16", "bee_keeping": "17", "belly_dancing": "18", "bench_pressing": "19", "bending_back": "20", "bending_metal": "21", "biking_through_snow": "22", "blasting_sand": "23", "blowing_glass": "24", "blowing_leaves": "25", "blowing_nose": "26", "blowing_out_candles": "27", "bobsledding": "28", "bookbinding": "29", "bouncing_on_trampoline": "30", "bowling": "31", "braiding_hair": "32", "breading_or_breadcrumbing": "33", "breakdancing": "34", "brush_painting": "35", "brushing_hair": "36", "brushing_teeth": "37", "building_cabinet": "38", "building_shed": "39", "bungee_jumping": "40", "busking": "41", "canoeing_or_kayaking": "42", "capoeira": "43", "carrying_baby": "44", "cartwheeling": "45", "carving_pumpkin": "46", "catching_fish": "47", "catching_or_throwing_baseball": "48", "catching_or_throwing_frisbee": "49", "catching_or_throwing_softball": "50", "celebrating": "51", "changing_oil": "52", "changing_wheel": "53", "checking_tires": "54", "cheerleading": "55", "chopping_wood": "56", "clapping": "57", "clay_pottery_making": "58", "clean_and_jerk": "59", "cleaning_floor": "60", "cleaning_gutters": "61", "cleaning_pool": "62", "cleaning_shoes": "63", "cleaning_toilet": "64", "cleaning_windows": "65", "climbing_a_rope": "66", "climbing_ladder": "67", "climbing_tree": "68", "contact_juggling": "69", "cooking_chicken": "70", "cooking_egg": "71", "cooking_on_campfire": "72", "cooking_sausages": "73", "counting_money": "74", "country_line_dancing": "75", "cracking_neck": "76", "crawling_baby": "77", "crossing_river": "78", "crying": "79", "curling_hair": "80", "cutting_nails": "81", "cutting_pineapple": "82", "cutting_watermelon": "83", "dancing_ballet": "84", "dancing_charleston": "85", "dancing_gangnam_style": "86", "dancing_macarena": "87", "deadlifting": "88", "decorating_the_christmas_tree": "89", "digging": "90", "dining": "91", "disc_golfing": "92", "diving_cliff": "93", "dodgeball": "94", "doing_aerobics": "95", "doing_laundry": "96", "doing_nails": "97", "drawing": "98", "dribbling_basketball": "99", "drinking": "100", "drinking_beer": "101", "drinking_shots": "102", "driving_car": "103", "driving_tractor": "104", "drop_kicking": "105", "drumming_fingers": "106", "dunking_basketball": "107", "dying_hair": "108", "eating_burger": "109", "eating_cake": "110", "eating_carrots": "111", "eating_chips": "112", "eating_doughnuts": "113", "eating_hotdog": "114", "eating_ice_cream": "115", "eating_spaghetti": "116", "eating_watermelon": "117", "egg_hunting": "118", "exercising_arm": "119", "exercising_with_an_exercise_ball": "120", "extinguishing_fire": "121", "faceplanting": "122", "feeding_birds": "123", "feeding_fish": "124", "feeding_goats": "125", "filling_eyebrows": "126", "finger_snapping": "127", "fixing_hair": "128", "flipping_pancake": "129", "flying_kite": "130", "folding_clothes": "131", "folding_napkins": "132", "folding_paper": "133", "front_raises": "134", "frying_vegetables": "135", "garbage_collecting": "136", "gargling": "137", "getting_a_haircut": "138", "getting_a_tattoo": "139", "giving_or_receiving_award": "140", "golf_chipping": "141", "golf_driving": "142", "golf_putting": "143", "grinding_meat": "144", "grooming_dog": "145", "grooming_horse": "146", "gymnastics_tumbling": "147", "hammer_throw": "148", "headbanging": "149", "headbutting": "150", "high_jump": "151", "high_kick": "152", "hitting_baseball": "153", "hockey_stop": "154", "holding_snake": "155", "hopscotch": "156", "hoverboarding": "157", "hugging": "158", "hula_hooping": "159", "hurdling": "160", "hurling_(sport)": "161", "ice_climbing": "162", "ice_fishing": "163", "ice_skating": "164", "ironing": "165", "javelin_throw": "166", "jetskiing": "167", "jogging": "168", "juggling_balls": "169", "juggling_fire": "170", "juggling_soccer_ball": "171", "jumping_into_pool": "172", "jumpstyle_dancing": "173", "kicking_field_goal": "174", "kicking_soccer_ball": "175", "kissing": "176", "kitesurfing": "177", "knitting": "178", "krumping": "179", "laughing": "180", "laying_bricks": "181", "long_jump": "182", "lunge": "183", "making_a_cake": "184", "making_a_sandwich": "185", "making_bed": "186", "making_jewelry": "187", "making_pizza": "188", "making_snowman": "189", "making_sushi": "190", "making_tea": "191", "marching": "192", "massaging_back": "193", "massaging_feet": "194", "massaging_legs": "195", "massaging_person's_head": "196", "milking_cow": "197", "mopping_floor": "198", "motorcycling": "199", "moving_furniture": "200", "mowing_lawn": "201", "news_anchoring": "202", "opening_bottle": "203", "opening_present": "204", "paragliding": "205", "parasailing": "206", "parkour": "207", "passing_American_football_(in_game)": "208", "passing_American_football_(not_in_game)": "209", "peeling_apples": "210", "peeling_potatoes": "211", "petting_animal_(not_cat)": "212", "petting_cat": "213", "picking_fruit": "214", "planting_trees": "215", "plastering": "216", "playing_accordion": "217", "playing_badminton": "218", "playing_bagpipes": "219", "playing_basketball": "220", "playing_bass_guitar": "221", "playing_cards": "222", "playing_cello": "223", "playing_chess": "224", "playing_clarinet": "225", "playing_controller": "226", "playing_cricket": "227", "playing_cymbals": "228", "playing_didgeridoo": "229", "playing_drums": "230", "playing_flute": "231", "playing_guitar": "232", "playing_harmonica": "233", "playing_harp": "234", "playing_ice_hockey": "235", "playing_keyboard": "236", "playing_kickball": "237", "playing_monopoly": "238", "playing_organ": "239", "playing_paintball": "240", "playing_piano": "241", "playing_poker": "242", "playing_recorder": "243", "playing_saxophone": "244", "playing_squash_or_racquetball": "245", "playing_tennis": "246", "playing_trombone": "247", "playing_trumpet": "248", "playing_ukulele": "249", "playing_violin": "250", "playing_volleyball": "251", "playing_xylophone": "252", "pole_vault": "253", "presenting_weather_forecast": "254", "pull_ups": "255", "pumping_fist": "256", "pumping_gas": "257", "punching_bag": "258", "punching_person_(boxing)": "259", "push_up": "260", "pushing_car": "261", "pushing_cart": "262", "pushing_wheelchair": "263", "reading_book": "264", "reading_newspaper": "265", "recording_music": "266", "riding_a_bike": "267", "riding_camel": "268", "riding_elephant": "269", "riding_mechanical_bull": "270", "riding_mountain_bike": "271", "riding_mule": "272", "riding_or_walking_with_horse": "273", "riding_scooter": "274", "riding_unicycle": "275", "ripping_paper": "276", "robot_dancing": "277", "rock_climbing": "278", "rock_scissors_paper": "279", "roller_skating": "280", "running_on_treadmill": "281", "sailing": "282", "salsa_dancing": "283", "sanding_floor": "284", "scrambling_eggs": "285", "scuba_diving": "286", "setting_table": "287", "shaking_hands": "288", "shaking_head": "289", "sharpening_knives": "290", "sharpening_pencil": "291", "shaving_head": "292", "shaving_legs": "293", "shearing_sheep": "294", "shining_shoes": "295", "shooting_basketball": "296", "shooting_goal_(soccer)": "297", "shot_put": "298", "shoveling_snow": "299", "shredding_paper": "300", "shuffling_cards": "301", "side_kick": "302", "sign_language_interpreting": "303", "singing": "304", "situp": "305", "skateboarding": "306", "ski_jumping": "307", "skiing_(not_slalom_or_crosscountry)": "308", "skiing_crosscountry": "309", "skiing_slalom": "310", "skipping_rope": "311", "skydiving": "312", "slacklining": "313", "slapping": "314", "sled_dog_racing": "315", "smoking": "316", "smoking_hookah": "317", "snatch_weight_lifting": "318", "sneezing": "319", "sniffing": "320", "snorkeling": "321", "snowboarding": "322", "snowkiting": "323", "snowmobiling": "324", "somersaulting": "325", "spinning_poi": "326", "spray_painting": "327", "spraying": "328", "springboard_diving": "329", "squat": "330", "sticking_tongue_out": "331", "stomping_grapes": "332", "stretching_arm": "333", "stretching_leg": "334", "strumming_guitar": "335", "surfing_crowd": "336", "surfing_water": "337", "sweeping_floor": "338", "swimming_backstroke": "339", "swimming_breast_stroke": "340", "swimming_butterfly_stroke": "341", "swing_dancing": "342", "swinging_legs": "343", "swinging_on_something": "344", "sword_fighting": "345", "tai_chi": "346", "taking_a_shower": "347", "tango_dancing": "348", "tap_dancing": "349", "tapping_guitar": "350", "tapping_pen": "351", "tasting_beer": "352", "tasting_food": "353", "testifying": "354", "texting": "355", "throwing_axe": "356", "throwing_ball": "357", "throwing_discus": "358", "tickling": "359", "tobogganing": "360", "tossing_coin": "361", "tossing_salad": "362", "training_dog": "363", "trapezing": "364", "trimming_or_shaving_beard": "365", "trimming_trees": "366", "triple_jump": "367", "tying_bow_tie": "368", "tying_knot_(not_on_a_tie)": "369", "tying_tie": "370", "unboxing": "371", "unloading_truck": "372", "using_computer": "373", "using_remote_controller_(not_gaming)": "374", "using_segway": "375", "vault": "376", "waiting_in_line": "377", "walking_the_dog": "378", "washing_dishes": "379", "washing_feet": "380", "washing_hair": "381", "washing_hands": "382", "water_skiing": "383", "water_sliding": "384", "watering_plants": "385", "waxing_back": "386", "waxing_chest": "387", "waxing_eyebrows": "388", "waxing_legs": "389", "weaving_basket": "390", "welding": "391", "whistling": "392", "windsurfing": "393", "wrapping_present": "394", "wrestling": "395", "writing": "396", "yawning": "397", "yoga": "398", "zumba": "399"}

**Comment by mx-mark** [comment]
@yanmingchao2 What do you mean that you assign the class_map.json to train_data_path? If you did that, you confuse the meaning of the label map, you should build the training data as following file https://github.com/mx-mark/VideoTransformer-pytorch/blob/main/demo/kinetics400_train_list_videos_25fps.txt

**Comment by yanmingchao2** [comment]
thank you for your reply!
