### ISSUE TITLE
How do we load ImageNet-21k ViT weights?

### ISSUE THREAD

**Issue by Darktex** [mx-mark/VideoTransformer-pytorch#19]
Hi guys, thanks for open sourcing this repo!

I see that your pretrained K600 models were initialized from the ViT ImageNet-21k weights. Can you share a snippet on how you initialized them? Did you use the models from `timm`?

Thanks!

**Comment by mx-mark** [comment]
@Darktex The code can be found in https://github.com/mx-mark/VideoTransformer-pytorch/blob/194cae69722eb5efad031c59f4ff03bc60633fa8/weight_init.py#L107

**Comment by mx-mark** [comment]
@Darktex The pre-train model is converted by others from the original repo  https://github.com/google-research/vision_transformer.

**Comment by Darktex** [comment]
Thanks @mx-mark ! Would you be able to add the ImageNet21k converted model to Google Drive for download?

**Comment by Darktex** [comment]
Thank you!
