### ISSUE TITLE
can i have a dockerimage?

### ISSUE THREAD

**Issue by SangMyeongWoh** [mx-mark/VideoTransformer-pytorch#2]
core dumped error occur while run script.

can i have a docker images?

**Comment by mx-mark** [comment]
os.environ['NCCL_SOCKET_IFNAME'] = args.nccl_ifname #'lan1'

**Comment by mx-mark** [comment]
> 

Would you mind to comment out the code 'os.environ['NCCL_SOCKET_IFNAME'] = args.nccl_ifname #'lan1'' in the line 107 of model_pretrain,py, and to see if it works?

**Comment by SangMyeongWoh** [comment]
> > 
> 
> Would you mind to comment out the code 'os.environ['NCCL_SOCKET_IFNAME'] = args.nccl_ifname #'lan1'' in the line 107 of model_pretrain,py, and to see if it works?

nothing changed T^T

i used model_inference.py and it happend while importing

model_inference.py, line 8
import data_transform as T

**Comment by mx-mark** [comment]
@SangMyeongWoh fine, we will build a notebook to make the model inference more convenient

**Comment by SangMyeongWoh** [comment]
thanks for your effort.
But core dumped error not solved
it occurs when import all of your code

Ex)
from video_transformer import ViViT

Segmentation fault (core dumped)

do you have any idea??

**Comment by SangMyeongWoh** [comment]
> Owner

thanks for your effort!
