### ISSUE TITLE
What is the final score of maskfeat?

### ISSUE THREAD

**Issue by daidaiershidi** [mx-mark/VideoTransformer-pytorch#21]

**Comment by mx-mark** [comment]
@daidaiershidi I think it should be the same as the original paper. We have no extract score on Kinetics but have pretrained MaskFeat on ImageNet, reaching a similar result as its paper (ViT-B: 84.0, ViT-L: 85.9).

**Comment by mx-mark** [comment]
@daidaiershidi We have no exact score on Kinetics but have pretrained on ImageNet1k, reaching a similar score as the original paper (ViT-B: 84.0, ViT-L: 85.9).

**Comment by daidaiershidi** [comment]
Could you please release the code on imagenet? I tried to reproduce 300 epochs of pre-training and 100 epochs of finetune and only got a top1 score of 81.6, much lower than the score in the paper (83.6). I don't know what detail is wrong, it's confusing... ...

**Comment by mx-mark** [comment]
@daidaiershidi It is belongs to a part of a project. We will release the code in the next few weeks.

**Comment by RachelTeamo** [comment]
I'm looking forward to the code on Imagenet. When will it be released? Thanks a lot.

**Comment by daidaiershidi** [comment]
@RechelTeamo The official project has been released. https://github.com/facebookresearch/SlowFast/blob/main/projects/maskfeat/README.md

**Comment by RachelTeamo** [comment]
Thanks again!
