### ISSUE TITLE
Maskfeat downstream task performance

### ISSUE THREAD

**Issue by WHlTE-N0lSE** [mx-mark/VideoTransformer-pytorch#6]
I tried to finetune a classifier with the maskfeat pretrained weights you provided, but the final performance was terrible (UCF101 Acc@top1=52%). What is your performance with finetune maskfeat? and what are your mvit finetune settings?

**Comment by mx-mark** [comment]
@WHlTE-N0lSE Firstly, the MaskFeat has not been trained so long, and maybe can not generalize well. Second, the MaskFeat relies heavily on finetune recipe to tune, the detailed finetune settings can be found in the original paper which we almost follow it.
