### ISSUE TITLE
the format of train_file.txt and loaded self-supervised pretrain checkpoints

### ISSUE THREAD

**Issue by happy-lifi** [mx-mark/VideoTransformer-pytorch#8]
Hi, can you provide train_file.txt, val_file.txt and test_file.txt? My email is haosen.yang.6@gamil.com.By the way, I would like to share with you how to train model loaded with self-supervised pretrain checkpoints.

**Comment by mx-mark** [comment]
@happy-lifi sorry, why you need the detailed data list? Because i think the train list is depends on the data you owned in your disk. If you need the build script, i will share it to you.

**Comment by happy-lifi** [comment]
I want to make sure my data is consistent with yours to reach your performance. You can send your script and *.txt to my email(haosen.yang.6@gamil.com).Thanks!

**Comment by mx-mark** [comment]
@happy-lifi i just upload the annotation file in the demo folder, you can check it.
