### ISSUE TITLE
error happened when I run dataset.py

### ISSUE THREAD

**Issue by nlpofwhat** [mx-mark/VideoTransformer-pytorch#9]
error information：File "D:\anaconda3\envs\adarnn\lib\site-packages\torchvision\transforms\functional.py", line 494, in resized_crop
    assert _is_pil_image(img), 'img should be PIL Image'
AssertionError: img should be PIL Image

my configuration: win10,python3.7，torch 1.6.0,
Your apply would be appreciated! Thank you very much!

**Comment by mx-mark** [comment]
@nlpofwhat it looks like the environment problem. maybe the tensor transform operation needs higher version of torch and torchvision. The version we used in the experiment is torch-1.10.2 and torchversion-0.11.3

**Comment by nlpofwhat** [comment]
thanks a lot.
